name: Skrautás ehf.
tagline: Grafarvogsblaðið, Árbæjarblaðið og Grafarholtsblaðið
phoneLabel: Ritstjórn og auglýsingar
phone: "698 2844"
emails:
  grafarvogsbladid: gv@skrautas.is
  arbaejarbladid: abl@skrautas.is
  grafarholtsbladid: gv@skrautas.is
